### ISSUE TITLE
Strange delete action on dumpmap

### ISSUE THREAD

**Issue by ShinIce** [FOSDEM/maps#120]
Hi,

just finished creating the stand on level 1 of the K building, so it was time for a new commit...but...

docker run --rm --name fosdem-map -v $(pwd):/data c3nav/c3nav dumpmap
logs
maps
maps-2017
maps-2017-sat
maps-2017-sun
Operations to perform:
  Apply all migrations: access, admin, auth, contenttypes, mapdata, sessions
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.

### dumping map...
Writing Map Packages…
- Created: maps-2017/arealocations/K_Level1_1.json
- Created: maps-2017/arealocations/K_Level1_10.json
- Created: maps-2017/arealocations/K_Level1_11.json
- Created: maps-2017/arealocations/K_Level1_12.json
- Created: maps-2017/arealocations/K_Level1_13.json
- Created: maps-2017/arealocations/K_Level1_14.json
- Created: maps-2017/arealocations/K_Level1_15.json
- Created: maps-2017/arealocations/K_Level1_16.json
- Created: maps-2017/arealocations/K_Level1_17.json
- Created: maps-2017/arealocations/K_Level1_18.json
- Created: maps-2017/arealocations/K_Level1_19.json
- Created: maps-2017/arealocations/K_Level1_2.json
- Created: maps-2017/arealocations/K_Level1_20.json
- Created: maps-2017/arealocations/K_Level1_21.json
- Created: maps-2017/arealocations/K_Level1_3.json
- Created: maps-2017/arealocations/K_Level1_4.json
- Created: maps-2017/arealocations/K_Level1_5.json
- Created: maps-2017/arealocations/K_Level1_6.json
- Created: maps-2017/arealocations/K_Level1_7.json
- Created: maps-2017/arealocations/K_Level1_8.json
- Created: maps-2017/arealocations/K_Level1_9.json
- Deleted: maps-2017/arealocations/545e9d1c5a54f.json
- Deleted: maps-2017/arealocations/545fcff04b16b.json
- Deleted: maps-2017/arealocations/aw1120.json
- Deleted: maps-2017/arealocations/aw1124.json
- Deleted: maps-2017/arealocations/aw1128.json
- Deleted: maps-2017/arealocations/cloakroom.json
- Deleted: maps-2017/arealocations/h1301_cornil.json
- Deleted: maps-2017/arealocations/h1302_depage.json
- Deleted: maps-2017/arealocations/h1308_rolin.json
- Deleted: maps-2017/arealocations/h1309_van_rijn.json
- Deleted: maps-2017/arealocations/h2211.json
- Deleted: maps-2017/arealocations/h2213.json
- Deleted: maps-2017/arealocations/h2214.json
- Deleted: maps-2017/arealocations/h2215_ferrer.json
- Deleted: maps-2017/arealocations/infodesk-h.json
- Deleted: maps-2017/arealocations/j-wc-1.json
- Deleted: maps-2017/arealocations/j-wc-2.json
- Deleted: maps-2017/arealocations/janson.json
- Deleted: maps-2017/arealocations/k3201.json
- Deleted: maps-2017/arealocations/k3401.json
- Deleted: maps-2017/arealocations/k3601.json
- Deleted: maps-2017/arealocations/k4201.json
- Deleted: maps-2017/arealocations/k4401.json
- Deleted: maps-2017/arealocations/k4601.json
- Deleted: maps-2017/arealocations/u-square.json
- Deleted: maps-2017/arealocations/ua2114_baudoux.json
- Deleted: maps-2017/arealocations/ua2220_guillissen.json
- Deleted: maps-2017/arealocations/ub2252a_lameere.json
- Deleted: maps-2017/arealocations/ud2120_chavanne.json
- Deleted: maps-2017/arealocations/ud2218a.json
- Deleted: maps-2017/levels/0-1.json
- Deleted: maps-2017/levels/0.json
- Deleted: maps-2017/levels/1-2.json
- Deleted: maps-2017/levels/1.json
- Deleted: maps-2017/levels/2-3.json
- Deleted: maps-2017/levels/2.json
- Deleted: maps-2017/levels/3.json
- Deleted: maps-2017-sat/arealocations/545e9d1c5a54f.json
- Deleted: maps-2017-sat/arealocations/545fcff04b16b.json
- Deleted: maps-2017-sat/arealocations/aw1120.json
- Deleted: maps-2017-sat/arealocations/aw1124.json
- Deleted: maps-2017-sat/arealocations/aw1128.json
- Deleted: maps-2017-sat/arealocations/cloakroom.json
- Deleted: maps-2017-sat/arealocations/h1301_cornil.json
- Deleted: maps-2017-sat/arealocations/h1302_depage.json
- Deleted: maps-2017-sat/arealocations/h1308_rolin.json
- Deleted: maps-2017-sat/arealocations/h1309_van_rijn.json
- Deleted: maps-2017-sat/arealocations/h2211.json
- Deleted: maps-2017-sat/arealocations/h2213.json
- Deleted: maps-2017-sat/arealocations/h2214.json
- Deleted: maps-2017-sat/arealocations/h2215_ferrer.json
- Deleted: maps-2017-sat/arealocations/infodesk-h.json
- Deleted: maps-2017-sat/arealocations/j-wc-1.json
- Deleted: maps-2017-sat/arealocations/j-wc-2.json
- Deleted: maps-2017-sat/arealocations/janson.json
- Deleted: maps-2017-sat/arealocations/k3201.json
- Deleted: maps-2017-sat/arealocations/k3401.json
- Deleted: maps-2017-sat/arealocations/k3601.json
- Deleted: maps-2017-sat/arealocations/k4201.json
- Deleted: maps-2017-sat/arealocations/k4401.json
- Deleted: maps-2017-sat/arealocations/k4601.json
- Deleted: maps-2017-sat/arealocations/u-square.json
- Deleted: maps-2017-sat/arealocations/ua2114_baudoux.json
- Deleted: maps-2017-sat/arealocations/ua2220_guillissen.json
- Deleted: maps-2017-sat/arealocations/ub2252a_lameere.json
- Deleted: maps-2017-sat/arealocations/ud2120_chavanne.json
- Deleted: maps-2017-sat/arealocations/ud2218a.json
- Deleted: maps-2017-sat/levels/0-1.json
- Deleted: maps-2017-sat/levels/0.json
- Deleted: maps-2017-sat/levels/1-2.json
- Deleted: maps-2017-sat/levels/1.json
- Deleted: maps-2017-sat/levels/2-3.json
- Deleted: maps-2017-sat/levels/2.json
- Deleted: maps-2017-sat/levels/3.json
- Deleted: maps-2017-sun/arealocations/545e9d1c5a54f.json
- Deleted: maps-2017-sun/arealocations/545fcff04b16b.json
- Deleted: maps-2017-sun/arealocations/aw1120.json
- Deleted: maps-2017-sun/arealocations/aw1124.json
- Deleted: maps-2017-sun/arealocations/aw1128.json
- Deleted: maps-2017-sun/arealocations/cloakroom.json
- Deleted: maps-2017-sun/arealocations/h1301_cornil.json
- Deleted: maps-2017-sun/arealocations/h1302_depage.json
- Deleted: maps-2017-sun/arealocations/h1308_rolin.json
- Deleted: maps-2017-sun/arealocations/h1309_van_rijn.json
- Deleted: maps-2017-sun/arealocations/h2211.json
- Deleted: maps-2017-sun/arealocations/h2213.json
- Deleted: maps-2017-sun/arealocations/h2214.json
- Deleted: maps-2017-sun/arealocations/h2215_ferrer.json
- Deleted: maps-2017-sun/arealocations/infodesk-h.json
- Deleted: maps-2017-sun/arealocations/j-wc-1.json
- Deleted: maps-2017-sun/arealocations/j-wc-2.json
- Deleted: maps-2017-sun/arealocations/janson.json
- Deleted: maps-2017-sun/arealocations/k3201.json
- Deleted: maps-2017-sun/arealocations/k3401.json
- Deleted: maps-2017-sun/arealocations/k3601.json
- Deleted: maps-2017-sun/arealocations/k4201.json
- Deleted: maps-2017-sun/arealocations/k4401.json
- Deleted: maps-2017-sun/arealocations/k4601.json
- Deleted: maps-2017-sun/arealocations/u-square.json
- Deleted: maps-2017-sun/arealocations/ua2114_baudoux.json
- Deleted: maps-2017-sun/arealocations/ua2220_guillissen.json
- Deleted: maps-2017-sun/arealocations/ub2252a_lameere.json
- Deleted: maps-2017-sun/arealocations/ud2120_chavanne.json
- Deleted: maps-2017-sun/arealocations/ud2218a.json
- Deleted: maps-2017-sun/levels/0-1.json
- Deleted: maps-2017-sun/levels/1-2.json
- Deleted: maps-2017-sun/levels/1.json
- Deleted: maps-2017-sun/levels/2-3.json
- Deleted: maps-2017-sun/levels/2.json
- Deleted: maps-2017-sun/levels/3.json

Don't know exactly why all this stuff has been deleted but I only created maps-2017/arealocations/K_Level1_[1-21].json

Any idea? Actually I'm not commiting :-)

**Comment by cbeyls** [comment]
I don't know but I did some tests today and I always get "Sorry, no Route could be found." unless source and destination are right next to each other. Could it be related ? The nav site is unusable in the current state, I hope it will be fixed before FOSDEM.

**Comment by ShinIce** [comment]
Hi cbeyls,

no, this should not be the problem since I'm working on a local instance on my system.
It is interesting since the route works here. Can you tell what route you had?

**Comment by cbeyls** [comment]
Sorry for the unrelated issue. I only tested on the live website.
Routes like these don't return any result:

http://nav.fosdem.org/r/h2213/ud2218a/
http://nav.fosdem.org/r/janson/infodesk-h/
Even inside the same building:
http://nav.fosdem.org/r/k4201/k3201/

**Comment by markvdb** [comment]
cbeyls: moving your routing issue to #125 . It's more or less of a known issue, but useful as a reminder...

**Comment by ShinIce** [comment]
atm i only committed the new stands without touching the deleted ones.

**Comment by ShinIce** [comment]
can be closed :)
