### ISSUE TITLE
Missing room: AW1.126

### ISSUE THREAD

**Issue by cbeyls** [FOSDEM/maps#121]
This room is located next to AW1.124 in the AW building and it's missing.

**Comment by ShinIce** [comment]
looks like a typo since aw1.128 is next to aw1.124 and not aw1.126
Will fix it :)

**Comment by ShinIce** [comment]
fixed with commit 83d53d2

**Comment by cbeyls** [comment]
The room image needs to be fixed too: https://github.com/FOSDEM/maps/blob/master/sources/aw-1.png
